=== mybatis/mybatis-3/src/test/java/com/ibatis/sqlmap/engine/builder/sql-map-2.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!ELEMENT sqlMap (typeAlias* | cacheModel* | resultMap* | parameterMap* | sql* | statement* | insert* | update* | delete* | select* | procedure*)+>
<!ATTLIST sqlMap
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>

<!ELEMENT parameterMap (parameter+)>
<!ATTLIST parameterMap
id CDATA #REQUIRED
class CDATA #REQUIRED
>
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
property CDATA #REQUIRED
javaType CDATA #IMPLIED
jdbcType CDATA #IMPLIED
typeName CDATA #IMPLIED
nullValue CDATA #IMPLIED
mode (IN | OUT | INOUT) #IMPLIED
typeHandler CDATA #IMPLIED
resultMap CDATA #IMPLIED
numericScale CDATA #IMPLIED
>
<!ELEMENT resultMap (result*, discriminator?)>
<!ATTLIST resultMap
id CDATA #REQUIRED
class CDATA #REQUIRED
extends CDATA #IMPLIED
xmlName CDATA #IMPLIED
groupBy CDATA #IMPLIED
>
<!ELEMENT result EMPTY>
<!ATTLIST result
property CDATA #REQUIRED
javaType CDATA #IMPLIED
column CDATA #IMPLIED
columnIndex CDATA #IMPLIED
jdbcType CDATA #IMPLIED
nullValue CDATA #IMPLIED
select CDATA #IMPLIED
resultMap CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>
<!ELEMENT discriminator (subMap+)>
<!ATTLIST discriminator
javaType CDATA #REQUIRED
column CDATA #IMPLIED
columnIndex CDATA #IMPLIED
jdbcType CDATA #IMPLIED
nullValue CDATA #IMPLIED
typeHandler CDATA #IMPLIED
>
<!ELEMENT subMap EMPTY>
<!ATTLIST subMap
value CDATA #REQUIRED
resultMap CDATA #REQUIRED
>
<!ELEMENT cacheModel (flushInterval?, flushOnExecute*, property*)+>
<!ATTLIST cacheModel
id CDATA #REQUIRED
type CDATA #REQUIRED
readOnly (true | false) #IMPLIED
serialize (true | false) #IMPLIED
>
<!ELEMENT flushInterval EMPTY>
<!ATTLIST flushInterval
milliseconds CDATA #IMPLIED
seconds CDATA #IMPLIED
minutes CDATA #IMPLIED
hours CDATA #IMPLIED
>
<!ELEMENT flushOnExecute EMPTY>
<!ATTLIST flushOnExecute
statement CDATA #REQUIRED
>

<!ELEMENT property EMPTY>
<!ATTLIST property
name CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias
alias CDATA #REQUIRED
type CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST sql
id CDATA #REQUIRED
>

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT statement (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST statement
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
fetchSize CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
remapResults (true|false) #IMPLIED
timeout CDATA #IMPLIED
>

<!ELEMENT select (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST select
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE) #IMPLIED
fetchSize CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
remapResults (true|false) #IMPLIED
timeout CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA | include | dynamic | selectKey | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST insert
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
timeout CDATA #IMPLIED
>

<!ELEMENT selectKey (#PCDATA | include)*>
<!ATTLIST selectKey
resultClass CDATA #IMPLIED
keyProperty CDATA #IMPLIED
type (pre|post) #IMPLIED
>

<!ELEMENT update (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST update
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
timeout CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST delete
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
timeout CDATA #IMPLIED
>

<!ELEMENT procedure (#PCDATA | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST procedure
id CDATA #REQUIRED
parameterMap CDATA #IMPLIED
parameterClass CDATA #IMPLIED
resultMap CDATA #IMPLIED
resultClass CDATA #IMPLIED
cacheModel CDATA #IMPLIED
fetchSize CDATA #IMPLIED
xmlResultName CDATA #IMPLIED
remapResults (true|false) #IMPLIED
timeout CDATA #IMPLIED
>

<!-- - - - - - - - - - - - - - - - - - - - - - - - -
                 DYNAMIC ELEMENTS
  - - - - - - - - - - - - - - - - - - - - - - - - -->

<!ELEMENT dynamic (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST dynamic
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
>

<!ELEMENT isNotNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotNull
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNull
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isNotPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotPropertyAvailable
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #REQUIRED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isPropertyAvailable
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #REQUIRED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isNotEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isGreaterThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterThan
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isGreaterEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isLessThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessThan
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isLessEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!ELEMENT isEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEmpty
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isNotEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEmpty
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isParameterPresent
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT isNotParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotParameterPresent
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!ELEMENT iterate (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST iterate
prepend CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false|iterate) #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
conjunction CDATA #IMPLIED
>

=== mybatis/mybatis-3/src/test/java/com/ibatis/jpetstore/persistence/sqlmapdao/sql/Account.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE sqlMap PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<sqlMap namespace="Account">

  <typeAlias alias="account" type="com.ibatis.jpetstore.domain.Account"/>

  <select id="getAccountByUsername" resultClass="account" parameterClass="string">
    SELECT
    SIGNON.USERNAME,
    ACCOUNT.EMAIL,
    ACCOUNT.FIRSTNAME,
    ACCOUNT.LASTNAME,
    ACCOUNT.STATUS,
    ACCOUNT.ADDR1 AS address1,
    ACCOUNT.ADDR2 AS address2,
    ACCOUNT.CITY,
    ACCOUNT.STATE,
    ACCOUNT.ZIP,
    ACCOUNT.COUNTRY,
    ACCOUNT.PHONE,
    PROFILE.LANGPREF AS languagePreference,
    PROFILE.FAVCATEGORY AS favouriteCategoryId,
    PROFILE.MYLISTOPT AS listOption,
    PROFILE.BANNEROPT AS bannerOption,
    BANNERDATA.BANNERNAME
    FROM ACCOUNT, PROFILE, SIGNON, BANNERDATA
    WHERE ACCOUNT.USERID = #username#
    AND SIGNON.USERNAME = ACCOUNT.USERID
    AND PROFILE.USERID = ACCOUNT.USERID
    AND PROFILE.FAVCATEGORY = BANNERDATA.FAVCATEGORY
  </select>

  <select id="getAccountByUsernameAndPassword" resultClass="account" parameterClass="account">
    SELECT
    SIGNON.USERNAME,
    ACCOUNT.EMAIL,
    ACCOUNT.FIRSTNAME,
    ACCOUNT.LASTNAME,
    ACCOUNT.STATUS,
    ACCOUNT.ADDR1 AS address1,
    ACCOUNT.ADDR2 AS address2,
    ACCOUNT.CITY,
    ACCOUNT.STATE,
    ACCOUNT.ZIP,
    ACCOUNT.COUNTRY,
    ACCOUNT.PHONE,
    PROFILE.LANGPREF AS languagePreference,
    PROFILE.FAVCATEGORY AS favouriteCategoryId,
    PROFILE.MYLISTOPT AS listOption,
    PROFILE.BANNEROPT AS bannerOption,
    BANNERDATA.BANNERNAME
    FROM ACCOUNT, PROFILE, SIGNON, BANNERDATA
    WHERE ACCOUNT.USERID = #username#
    AND SIGNON.PASSWORD = #password#
    AND SIGNON.USERNAME = ACCOUNT.USERID
    AND PROFILE.USERID = ACCOUNT.USERID
    AND PROFILE.FAVCATEGORY = BANNERDATA.FAVCATEGORY
  </select>

  <update id="updateAccount" parameterClass="account">
    UPDATE ACCOUNT SET
    EMAIL = #email#,
    FIRSTNAME = #firstName#,
    LASTNAME = #lastName#,
    STATUS = #status#,
    ADDR1 = #address1#,
    ADDR2 = #address2:VARCHAR#,
    CITY = #city#,
    STATE = #state#,
    ZIP = #zip#,
    COUNTRY = #country#,
    PHONE = #phone#
    WHERE USERID = #username#
  </update>

  <insert id="insertAccount" parameterClass="account">
    INSERT INTO ACCOUNT
    (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
    (#email#, #firstName#, #lastName#, #status#, #address1#, #address2:VARCHAR#, #city#, #state#, #zip#, #country#,
    #phone#, #username#)
  </insert>

  <update id="updateProfile" parameterClass="account">
    UPDATE PROFILE SET
    LANGPREF = #languagePreference#,
    FAVCATEGORY = #favouriteCategoryId#,
    MYLISTOPT = #listOption#,
    BANNEROPT = #bannerOption#
    WHERE USERID = #username#
  </update>

  <insert id="insertProfile" parameterClass="account">
    INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES (#languagePreference#, #favouriteCategoryId#, #listOption#, #bannerOption#, #username#)
  </insert>

  <update id="updateSignon" parameterClass="account">
    UPDATE SIGNON SET PASSWORD = #password#
    WHERE USERNAME = #username#
  </update>

  <insert id="insertSignon" parameterClass="account">
    INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES (#password#, #username#)
  </insert>

</sqlMap>

=== mybatis/mybatis-3/src/test/java/com/ibatis/sqlmap/maps/XmlStatements.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE sqlMap
    PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<sqlMap>

  <parameterMap id="xml-parameter-map" class="map">
    <parameter property="id"/>
  </parameterMap>

  <resultMap id="xml-account-result" class="hashmap">
    <result property="id" column="ACC_ID"/>
    <result property="firstName" column="ACC_FIRST_NAME"/>
    <result property="lastName" column="ACC_LAST_NAME"/>
    <result property="emailAddress" column="ACC_EMAIL"/>
    <result property="account" column="{id=ACC_ID}" select="getAccountXml"/>
  </resultMap>

  <resultMap id="xml-order-with-lines-result" class="hashmap" extends="lite-order-result-by-name">
    <result property="lineItems" javaType="map" column="{value=ORD_ID}" select="getLineItemsForOrderXml"/>
  </resultMap>

  <select id="getAccountXmlExternalMaps"
          parameterMap="xml-parameter-map"
          resultMap="xml-account-result">
    select
    ACC_ID,
    ACC_FIRST_NAME,
    ACC_LAST_NAME,
    ACC_EMAIL
    from ACCOUNT
    where ACC_ID = ?
  </select>

  <select id="getAccountXml"
          parameterClass="map"
          resultClass="hashmap">
    select
    ACC_ID as id,
    ACC_FIRST_NAME as firstName,
    ACC_LAST_NAME as lastName,
    ACC_EMAIL as emailAddress
    from ACCOUNT
    where ACC_ID = #id#
  </select>

  <select id="getLineItemsForOrderXml"
          parameterClass="map"
          resultClass="hashmap">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,
    LIN_ITM_CODE as itemCode,
    LIN_QUANTITY as quantity,
    LIN_PRICE as price
    from LINE_ITEM where LIN_ORD_ID = #value#
  </select>

  <select id="getOrderXml"
          parameterClass="map"
          resultMap="xml-order-with-lines-result">
    select * from ORDERS where ORD_ID = #id#
  </select>


</sqlMap>

=== mybatis/mybatis-3/src/test/java/com/ibatis/sqlmap/maps/ResultObjectFactoryStatements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN" "http://ibatis.apache.org/dtd/sql-map-2.dtd">
<sqlMap namespace="ResultObjectFactoryStatements">

  <resultMap id="itemResultROF" class="com.testdomain.IItem">
    <result column="itemid" property="itemId"/>
    <result column="productid" property="productId"/>
    <result column="listprice" property="listPrice"/>
    <result column="unitcost" property="unitCost"/>
    <result column="status" property="status"/>
    <result column="attr1" property="attribute1"/>
    <result column="attr2" property="attribute2"/>
    <result column="attr3" property="attribute3"/>
    <result column="attr4" property="attribute4"/>
    <result column="attr5" property="attribute5"/>
    <result column="{supplierId=supplier}" property="supplier" select="getSupplierByIdROF"/>
  </resultMap>

  <resultMap id="supplierResultROF" class="com.testdomain.ISupplier">
    <result column="suppid" property="supplierId"/>
    <result column="name" property="name"/>
    <result column="status" property="status"/>
    <result column="addr1" property="addressLine1"/>
    <result column="addr2" property="addressLine1"/>
    <result column="city" property="city"/>
    <result column="state" property="state"/>
    <result column="zip" property="zip"/>
    <result column="phone" property="phone"/>
  </resultMap>

  <select id="getAllItemsROF" resultMap="itemResultROF">
    select *
    from item
  </select>

  <select id="getSupplierByIdROF" resultMap="supplierResultROF" parameterClass="com.testdomain.ISupplierKey">
    select *
    from supplier
    where suppid = #supplierId#
  </select>
</sqlMap>

=== mybatis/mybatis-3/src/test/java/com/ibatis/sqlmap/maps/Multilist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE sqlMap
    PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<sqlMap>

  <resultMap id="categoryResultMap" class="com.testdomain.Category" groupBy="categoryId">
    <result property="categoryId" column="catid"/>
    <result property="name" column="catname"/>
    <result property="description" column="catdescn"/>
    <result property="productList" resultMap="productResultMap"/>
    <result property="itemList" resultMap="itemResultMap"/>
  </resultMap>


  <resultMap id="productResultMap" class="com.testdomain.Product">
    <result property="productId" column="productid"/>
    <result property="categoryId" column="category"/>
    <result property="name" column="prodname"/>
    <result property="description" column="proddescn"/>
  </resultMap>

  <resultMap id="itemResultMap" class="com.testdomain.Item">
    <result property="itemId" column="itemid"/>
    <result property="productId" column="productid"/>
    <result property="listPrice" column="listprice"/>
    <result property="unitCost" column="unitcost"/>
    <result property="supplierId" column="supplier"/>
    <result property="status" column="status"/>
    <result property="attribute1" column="attr1"/>
    <result property="quantity" column="qty"/>
  </resultMap>

  <select id="getAllCategoriesMap" resultMap="categoryResultMap">
    select
    c.catid, c.name as catname, c.descn as catdescn,
    p.productid, p.category, p.name as prodname,
    p.descn as proddescn, i.itemid, i.productid,
    i.listprice, i.unitcost, i.supplier, i.status,
    i.attr1, i.attr2, i.attr3, i.attr4, i.attr5,
    v.itemid, v.qty
    from category c, product p, item i, inventory v
    where c.catid = p.category
    and p.productid = i.productid
    and i.itemid = v.itemid
  </select>

</sqlMap>

=== mybatis/mybatis-3/src/test/java/com/ibatis/sqlmap/maps/LineItem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--

       Copyright 2009-2012 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.

-->

<!DOCTYPE sqlMap
    PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN"
    "http://ibatis.apache.org/dtd/sql-map-2.dtd">

<sqlMap>

  <resultMap id="missingParamCheckA" class="com.testdomain.LineItem">
    <result property="id" column="id"/>
    <result property="orderId" column="orderId"/>
    <result property="itemCode" column="itemCode"/>
  </resultMap>

  <resultMap id="missingParamCheckB" class="com.testdomain.LineItem" extends="missingParamCheckA">
    <result property="quantity" column="quantity"/>
    <result property="price" column="price"/>
  </resultMap>

  <select id="getAllLineItemProps" parameterClass="int" resultMap="missingParamCheckA">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,
    LIN_ITM_CODE as itemCode
    from LINE_ITEM where LIN_ORD_ID = #value#
  </select>

  <select id="getSomeLineItemProps" parameterClass="int" resultMap="missingParamCheckB">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,

    LIN_QUANTITY as quantity,
    LIN_PRICE as price
    from LINE_ITEM where LIN_ORD_ID = #value#
  </select>


  <select id="getLineItemsForOrder"
          parameterClass="java.lang.Integer"
          resultClass="com.testdomain.LineItem">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,
    LIN_ITM_CODE as itemCode,
    LIN_QUANTITY as quantity,
    LIN_PRICE as price
    from LINE_ITEM where LIN_ORD_ID = #value#
  </select>

  <insert id="insertLineItem" parameterClass="com.testdomain.LineItem">
    <selectKey resultClass="int" keyProperty="id" type="post">
      select 99 from LINE_ITEM where LIN_ID = 1 and LIN_ORD_ID=1
    </selectKey>
    insert into LINE_ITEM
    (LIN_ID, LIN_ORD_ID, LIN_ITM_CODE, LIN_QUANTITY, LIN_PRICE)
    values
    (#id#, #orderId#, #itemCode#, #quantity#, #price#)
  </insert>

  <insert id="insertLineItemOrDie" parameterClass="com.testdomain.LineItem">
    <selectKey resultClass="int" keyProperty="id" type="post">
      select 99 from LINE_ITEM where LIN_ID = 1 and LIN_ORD_ID=1
    </selectKey>
    insert into LINE_ITEM_LOL
    (LIN_ID, LIN_ORD_ID, LIN_ITM_CODE, LIN_QUANTITY, LIN_PRICE)
    values
    (#id#, #orderId#, #itemCode#, #quantity#, #price#)
  </insert>

  <insert id="insertLineItemPreKey" parameterClass="com.testdomain.LineItem">
    <selectKey resultClass="int" keyProperty="id">
      select 99 from LINE_ITEM where LIN_ID = 1 and LIN_ORD_ID=1
    </selectKey>
    insert into LINE_ITEM
    (LIN_ID, LIN_ORD_ID, LIN_ITM_CODE, LIN_QUANTITY, LIN_PRICE)
    values
    (#id#, #orderId#, #itemCode#, #quantity#, #price#)
  </insert>

  <insert id="insertLineItemNoKey" parameterClass="com.testdomain.LineItem">
    insert into LINE_ITEM
    (LIN_ID, LIN_ORD_ID, LIN_ITM_CODE, LIN_QUANTITY, LIN_PRICE)
    values
    (#id#, #orderId#, #itemCode#, #quantity#, #price#)
  </insert>

  <select id="getSpecificLineItem"
          parameterClass="java.util.HashMap"
          resultClass="com.testdomain.LineItem">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,
    LIN_ITM_CODE as itemCode,
    LIN_QUANTITY as quantity,
    LIN_PRICE as price
    from LINE_ITEM
    where LIN_ORD_ID = #orderId#
    and LIN_ID = #lineId#
  </select>

  <select id="getDynSpecificLineItem"
          parameterClass="java.util.HashMap"
          resultClass="com.testdomain.LineItem">
    select
    LIN_ID as id,
    LIN_ORD_ID as orderId,
    LIN_ITM_CODE as itemCode,
    LIN_QUANTITY as quantity,
    LIN_PRICE as price
    from LINE_ITEM
    where LIN_ORD_ID = #orderId#
    <dynamic>
      <isNotNull property="lineId">
        and LIN_ID = #lineId#
      </isNotNull>
    </dynamic>
  </select>

</sqlMap>
